canonifyurls = true
languageCode = "en-us"
title = "Tech @ Sparkfabrik"
pygmentsUseClasses = true

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
